version: '3'
services:
  adh-nginx:
    image: registry.cn-hangzhou.aliyuncs.com/awesome-digital-human/nginx:latest
    ports:
      - "8880:80"
      # - "8443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
  adh-web:
    image: "registry.cn-hangzhou.aliyuncs.com/awesome-digital-human/adh-web:main-latest"
    restart: always
    pull_policy: always
    networks:
      - shared_network
      - default
    # ports:
    #   - "3000:3000"
    volumes:
      - ./web/.env:/workspace/.env
  # awesome digital human server
  adh-api:
    image: "registry.cn-hangzhou.aliyuncs.com/awesome-digital-human/adh-api:main-latest"
    restart: always
    pull_policy: always
    networks:
      - shared_network
      - default
    # ports:
    #   - "8000:8000"
    volumes:
      - ./configs:/workspace/configs
# network
networks:
  shared_network:
    driver: bridge
    internal: true
